### ISSUE TITLE
1.9.1: issue with dist tar ball

### ISSUE THREAD

**Issue by kloczek** [kyz/libmspack#29] opened 2019-04-22 15:44 UTC
Looks like in this repo is maintained not one but two separated projects.
This makes a bit difficult to package (automatically) libmspack.
My suggestion is to separate those two projects into two repos (clone and move up each of the projects up in directory hierarchy and delete second project from the copies) or provide dist tar balls generated by "make distcheck" on the https://www.cabextract.org.uk/libmspack/ (because content of that page is not up to date).

**Comment by kyz** [comment] 2019-04-23 09:24
Both cabextract and libmspack have releases on https://www.cabextract.org.uk/, packagers should use the releases.

cabextract is directly linked to the libmspack sources, so I don't think splitting into multiple repos is appropriate.

libmspack, like cabextract is released when tested and ready, and made available as a tarball. All previous tarball releases remain in place. The current release is https://www.cabextract.org.uk/libmspack/libmspack-0.10.1alpha.tar.gz

**Comment by kyz** [comment] 2019-04-23 12:03
Closing this as a duplicate of https://github.com/kyz/libmspack/issues/30

**Closed by kyz** 2019-04-23 12:03 UTC
